# Workflow to deploy demo components (infrastructure)

name: Infra - Demo integration

# Controls when the action will run. 
on:
 workflow_dispatch:
    inputs:
      subscriptionId:
        description: 'SubscriptionId'
        required: true
      resourceGroupName:
        description: 'Resource group name'
        required: true
        default: 'rg-demo-ais'
      sqlServerName:
        description: 'SQL Server name'
        required: true
        default: 'sqlsrv'
      sqlLogin:
        description: 'SQL Login id'
        required: true
        default: 'adminuser'
      sqlLoginPwd:
        description: 'SQL Login pwd'
        required: true
        default: 'PassW0rd1!'
      sqlDatabase:
        description: 'SQL Database name'
        required: true
        default: 'usecase3'
      sqlDataFactory:
        description: 'DataFactory name'
        required: true
        default: 'adfdemo'
      funcAppName:
        description: 'Function name'
        required: true
        default: 'snow'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

      - name: deploy infra
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{github.event.inputs.subscriptionId}}
          resourceGroupName: ${{github.event.inputs.resourceGroupName}}
          template: ./infra/main-infra.bicep
          parameters: sqlserverName=${{github.event.inputs.sqlServerName}} sqllogin=${{github.event.inputs.sqlLogin}} sqlpassword=${{github.event.inputs.sqlLoginPwd}} sqlDatabase=${{github.event.inputs.sqlDatabase}} datafactory=${{github.event.inputs.sqlDataFactory}}

      - name: deploy Function plan
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{github.event.inputs.subscriptionId}}
          resourceGroupName: ${{github.event.inputs.resourceGroupName}}
          template: ./infra/az-function-plan.bicep
          parameters: appName=${{github.event.inputs.funcAppName}} 