# This deploys the blob storage account for integration use cases

name: Deploy Infra - storage account

# Controls when the action will run. 
on:
 workflow_dispatch:
    inputs:
      subscriptionId:
        description: 'SubscriptionId'
        required: true
        default: 'a7e948a0-d968-4731-801f-7053780b34fe'
      resourceGroupName:
        description: 'Resource group name'
        required: true
        default: 'LogicAppEastUS'
      storageAccountName:
        description: 'Storage account name'
        required: true
        default: 'startestusecase4'
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-infra-as-code:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

      - name: deploy_blobstorage
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{github.event.inputs.subscriptionId}}
          resourceGroupName: ${{github.event.inputs.resourceGroupName}}
          template: ./infra/iac_blobstorage.bicep
          parameters: storageAccountName=${{github.event.inputs.storageAccountName}}
